apiVersion: garden.io/v1
kind: Project
name: garden-remote
defaultEnvironment: development

environments:
  - name: development
  - name: production

providers:
  - name: exec
    environments: [ development, production ]
  - name: terraform
    environments: [ production ]