apiVersion: garden.io/v1
kind: Project
name: garden-remote
defaultEnvironment: development

environments:
  - name: development
  - name: production

providers:
  - name: exec
    environments: [ development, production ]

---
kind: Run
name: run-remote-task
type: exec
#disabled: "${environment.name == 'development'}"
environments:
  - production
spec:
  command: ["sh", "-c", "echo 'Hello from garden-remote in development'"]